---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "flye"
description: Assemble long reads into a metagenome with Flye
keywords:
  - assembly
  - nanopore
  - long reads
  - metagenome
tools:
  - "flye":
      description: De novo assembler for single-molecule sequencing reads
      homepage: https://github.com/mikolmogorov/Flye
      documentation: https://github.com/mikolmogorov/Flye/blob/flye/docs/USAGE.md
      licence: ["BSD-3-Clause"]
      identifier: biotools:flye
input:
  - - meta:
        type: map
        description: Groovy Map containing sample or group information, e.g. `[ id:'group1' ]`
    - reads:
        type: file
        description: Sequencing reads in FastQ format
output:
  fasta:
    - - meta:
          type: map
          description: Groovy Map containing sample or group information, e.g. `[ id:'group1' ]`
      - "*.fasta":
          type: file
          description: Sequences in FASTA format
          pattern: "*.fasta"
  gfa:
    - - meta:
          type: map
          description: Groovy Map containing sample or group information, e.g. `[ id:'group1' ]`
      - "*.gfa":
          type: file
          description: Gfa
          pattern: "*.gfa"
  txt:
    - - meta:
          type: map
          description: Groovy Map containing sample or group information, e.g. `[ id:'group1' ]`
      - "*.txt":
          type: file
          description: Txt
          pattern: "*.txt"
  log:
    - - meta:
          type: map
          description: Groovy Map containing sample or group information, e.g. `[ id:'group1' ]`
      - "*.log":
          type: file
          description: Log
          pattern: "*.log"
  json:
    - - meta:
          type: map
          description: Groovy Map containing sample or group information, e.g. `[ id:'group1' ]`
      - "*.json":
          type: file
          description: Json
          pattern: "*.json"
  versions:
authors:
  - "@dsamoht"
maintainers:
  - "@dsamoht"
