---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "minimap"
description: Map long reads to an assembly with minimap2
keywords:
  - align
  - map
  - long reads
  - nanopore
  - sam
tools:
  - "minimap2":
      description: Versatile pairwise aligner for genomic and spliced nucleotide sequences
      homepage: https://github.com/lh3/minimap2
      documentation: https://lh3.github.io/minimap2/minimap2.html
      licence: ["MIT"]
      identifier: biotools:minimap2
input:
  - - meta_reads:
        type: map
        description: Meta reads
    - reads:
        type: file
        description: Sequencing reads in FastQ format
  - - meta_reference:
        type: map
        description: Meta reference
    - reference:
        type: file
        description: Reference assembly in FASTA format
output:
  sam:
    - - meta_reads:
          type: map
          description: Meta reads
      - "*.sam":
          type: file
          description: Alignments in SAM format
          pattern: "*.sam"
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@dsamoht"
maintainers:
  - "@dsamoht"
